apiVersion: v1
kind: ConfigMap
metadata:
  name: prober-config
  labels:
    app.kubernetes.io/name: prober
data:
  ONCALL_API_URL: http://oncall:8080 # Internal service URL for OnCall
  PROBER_SCRAPE_INTERVAL: "30"
  PROBER_LOG_LEVEL: DEBUG
  PROBER_METRICS_PORT: "9082"