---
apiVersion: v1
kind: Service
metadata:
  name: oncall
  annotations:
    prometheus.io/path: /metrics # <— path, по которому целевой под отдает метрики
    prometheus.io/port: "8888" # <— порт, соответствующий targetPort'у сервиса, с которого будут собираться метрики
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: oncall
  sessionAffinity: None
  ports:
    - name: main
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: metrics
      protocol: TCP
      port: 8888
      targetPort: 8888
